In [2]:
import numpy as np

## Creating numpy arrays

In [6]:
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(array1)
print(type(array1))

<class 'list'>
[1 2 3]
<class 'numpy.ndarray'>


In [7]:
print(array1.ndim)

1


In [8]:
list2 = [[1,2],[3,4]]
array2 = np.array(list2)
print(array2)
print(type(array2))
print(array2.ndim)

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>
2


## np.zeros() returns float value

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

## np.ones()

In [12]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [13]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

## np.full()

In [14]:
np.full(5,2)

array([2, 2, 2, 2, 2])

In [16]:
np.full((2,3),-2)

array([[-2, -2, -2],
       [-2, -2, -2]])

## np.arrange()

### np.array(range(start,stop,step))

In [18]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [19]:
np.arange(1,6)

array([1, 2, 3, 4, 5])

In [21]:
np.arange(4,12,2)

array([ 4,  6,  8, 10])

## np.linspace()

In [22]:
# np.linspace(start, stop, num_of_items_in_betn)
np.linspace(1,10,2)

array([ 1., 10.])

In [23]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [24]:
np.linspace((1,2),(5,10),5)

array([[ 1.,  2.],
       [ 2.,  4.],
       [ 3.,  6.],
       [ 4.,  8.],
       [ 5., 10.]])