In [1]:
import numpy as np

## Elementwise operation

In [2]:
a = np.array([[4,5,6],[5,7,9]])
b = np.array([[1,2,3],[3,4,5]])

In [3]:
a + b

array([[ 5,  7,  9],
       [ 8, 11, 14]])

In [4]:
a - b

array([[3, 3, 3],
       [2, 3, 4]])

## Matrix operations

In [5]:
a = np.array([[1,2],[3,4]])
b = np.array([[2,3],[5,6]])

In [6]:
a

array([[1, 2],
       [3, 4]])

In [7]:
b

array([[2, 3],
       [5, 6]])

In [8]:
np.dot(a,b)

array([[12, 15],
       [26, 33]])

In [9]:
c = np.array([[1,2,3], [3,4,5]])
d = np.array([[5,6],[7,8]])

In [10]:
np.dot(c,d)

ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

In [11]:
np.transpose(a)

array([[1, 3],
       [2, 4]])

In [13]:
np.trace(a)  #sum of diagonal elements

5

In [14]:
np.linalg.det(a)

-2.0000000000000004

## Broadcasting

In [15]:
a = np.array([[1,2],[3,4]])
b = np.array([10,20])

In [16]:
a

array([[1, 2],
       [3, 4]])

In [17]:
b

array([10, 20])

In [18]:
a + b

array([[11, 22],
       [13, 24]])

### Here b is repeated twice to match with dimensions of a

### Why numpy over pthon's for loop

In [ ]:
import numpy as np
import time

a = np.random.rand(1000000)