# NUmpy array types and type conversion

In [4]:
import numpy as np

a = np.array([1,2,3], dtype=np.int32)
b = np.array([1.0,2.0,3.9], dtype=np.float64)
c = np.array([True, False, True], dtype=np.bool_)

print(a.dtype)
print(b.dtype)
print(c.dtype)

int32
float64
bool


In [5]:
d = np.array([1,2,3], dtype=np.float64)

In [6]:
d

array([1., 2., 3.])

In [7]:
e = np.array([1.8,2.0,3.4], dtype=np.int32)
e

array([1, 2, 3])

In [8]:
f = np.array([True, False, True], dtype=np.int32)

In [9]:
f

array([1, 0, 1])

In [10]:
g = a.astype(np.float32)

In [11]:
g

array([1., 2., 3.], dtype=float32)

In [12]:
a

array([1, 2, 3])